### ISSUE TITLE
首页问题

### ISSUE THREAD

**Issue by secretgao** [Tomotoes/hexo-theme-tomotoes#11]
大佬你好，我用了你的皮肤做了博客 根据你的文档做的配置，但是我看你网上打开的时候有可以滚动之后进入博客 ，我怎么就直接进去了呢

**Comment by SimonAKing** [comment]
首页并不包括在主题中。

**Comment by phpios** [comment]
主题里，和你的博客效果也不太一样啊，貌似不是最新的

**Comment by SimonAKing** [comment]
哎，我很久没更新了。我把 node升级成了 node 10 之后，便不兼容 当前的 gulp，再加上最近很忙，就一直没弄。

**Comment by phpios** [comment]
哦， 理解。有空你在弄吧。 期待以后的优化

**Comment by SimonAKing** [comment]
谢谢 :D

**Comment by hubby1314** [comment]
大佬你好，我用了你的皮肤做了博客 根据你的文档做的配置，我的标签和分类都没有显示，页面上有个打赏的出现了？我是哪里配置的不对么

**Comment by MisterBoole** [comment]
大佬，首页的效果，在哪里能找到？？？跪求

**Comment by MisterBoole** [comment]
我看你那有语言包，我怎么配置？

**Comment by SimonAKing** [comment]
@StaminaWang  主题不包括首页

**Comment by story-has-you** [comment]
大佬，首页打算开源吗？？？

**Comment by SimonAKing** [comment]
@FangXiSaMa 暂时没有打算

**Comment by gitwarning** [comment]
大佬请问分类和标签为什么一直时打赏的页面呢？请问怎么改成文章的分类呢？多谢！

**Comment by SimonAKing** [comment]
主题项目最近马上更新 , 以及主页 和 关于页面 都会开源.
