### ISSUE TITLE
abbrlink配置应该如何设置呢？

### ISSUE THREAD

**Issue by lDaisy847800926** [Tomotoes/hexo-theme-tomotoes#2]
不管我怎么设置最后总是会报错？
# URL
url: http://ldaisy847800926.github.io/
root: /
permalink: /posts/:abbrlink/  # **一定要配置好这里，非常重要**
permalink_defaults:

**Comment by SimonAKing** [comment]
请先安装插件之后进行配置。
url: http://tomotoes.com/
root: /
permalink: /posts/:abbrlink/ 
permalink_defaults:

abbrlink:
空格alg: crc32  
空格rep: hex  
将其替换到根目录的配置文件，注意缩进，其中有空格的地方，我用汉字标识出来了。
