### ISSUE TITLE
请教这个pointer.cur文件的请求位置怎么总是不对 

### ISSUE THREAD

**Issue by hi-wendy** [Tomotoes/hexo-theme-tomotoes#4]
GET https://qq807595678.github.io/limedroid.github.io/tags/img/pointer.cur 404 ()

并且文件的请求在跳转后也会发生变化
https://qq807595678.github.io/img/pointer.cur 404 ()
这应该是哪里没配置好啊

**Comment by hi-wendy** [comment]
这是我的地址，有时间帮我看看谢谢啦https://qq807595678.github.io/limedroid.github.io

**Comment by SimonAKing** [comment]
在script.js 中搜索 cursor ，删除那条代码，并同步到 script.min.js
