### ISSUE TITLE
关于页面无法输入自己的信息

### ISSUE THREAD

**Issue by isGt93** [Tomotoes/hexo-theme-tomotoes#5]
root@gt:/home/git/My-blog/isGt93.github.io/source/about# cat index.md 
---
title: about
date: 2018-02-14 22:49:07
layout: about
comments: false
reward: false
---

## asdadsadasdasd
# da
*dasda*
#d#
a
sd

理论显示结果：
## asdadsadasdasd
# da
*dasda*
#d#
a
sd
实际显示结果：
空

**Comment by SimonAKing** [comment]
可在关于页面中写 html，不过style，script标签中的内容要缩成一行。
