### ISSUE TITLE
请问网页刚刚进去的页面包含在里面吗？

### ISSUE THREAD

**Issue by d2pq** [Tomotoes/hexo-theme-tomotoes#6]
![image](https://user-images.githubusercontent.com/24861806/37252824-425c2e2a-2563-11e8-869c-f399a8140c3c.png)
![image](https://user-images.githubusercontent.com/24861806/37252832-632b6224-2563-11e8-8aad-d9d42682989c.png)

**Comment by SimonAKing** [comment]
不包括
