### ISSUE TITLE
旋转的立方体可以在哪里取消吗？另外Safari不会显示文章的TOC

### ISSUE THREAD

**Issue by Yuki-Judai** [Tomotoes/hexo-theme-tomotoes#7]
几个旋转的立方体可以在哪里取消吗？Safari打开温度升到60多度。

还有Safari不会显示文章的TOC。希望作者抽时间能兼容下Safari。:-)

**Comment by SimonAKing** [comment]
很抱歉，真的没有环境去兼容 Safari..  没钱买 Mac 啊 /(ㄒoㄒ)/~~

**Comment by Yuki-Judai** [comment]
好吧，遗憾。/(ㄒoㄒ)/~~。那旋转的立方体可以在哪里取消吗？
