### ISSUE TITLE
关于 文章截断 无法正常的问题？

### ISSUE THREAD

**Issue by zhupengfeivip** [Tomotoes/hexo-theme-tomotoes#9]
首先这个主题确实不错。感谢作者。然后请教一个问题，
以下是我的博客https://zhupengfeivip.github.io/
主页上有些问题，
1、主页上显示post.continue_reading，应该显示配置里的阅读全文的中文提示吧。
2、主页的内容裁剪不起作用。

配置如下
excerpt_render: true
excerpt_length: 175
excerpt_link: 阅读全文 »
mathjax: false
archive_yearly: true

**Comment by SimonAKing** [comment]
谢谢。
1. 阅读全文可以修改根目录配置文件中的 language: zh-CN
2. 文章格式设置为：文章摘要`<!-- more -->`文章内容，即可裁剪

**Comment by zhupengfeivip** [comment]
谢谢，我试一下。发自我的华为手机-------- 原始邮件 --------主题：Re: [Tomotoes/hexo-theme-tomotoes] 关于 文章截断 无法正常的问题？ (#9)发件人：Simon Ma 收件人：Tomotoes/hexo-theme-tomotoes 抄送：zhupengfeivip ,Author 谢谢。

阅读全文可以修改根目录配置文件中的 language: zh-CN
文章格式设置为：文章摘要文章内容，即可裁剪


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Tomotoes/hexo-theme-tomotoes","title":"Tomotoes/hexo-theme-tomotoes","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Tomotoes/hexo-theme-tomotoes"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Tomotoes in #9: 谢谢。\r\n1. 阅读全文可以修改根目录配置文件中的 language: zh-CN\r\n2. 文章格式设置为：文章摘要\u003c!--more--\u003e文章内容，即可裁剪"}],"action":{"name":"View Issue","url":"https://github.com/Tomotoes/hexo-theme-tomotoes/issues/9#issuecomment-381108926"}}}
